### ISSUE TITLE
Propozycja: LanguageTool (alternatywa dla Grammarly)

### ISSUE THREAD

**Issue by hexandcube** [Arturro43/privacy-links#1]
LanguageTool jest alternatywą dla Grammarly z otwartym kodem źródłowym, która wspiera więcej języków niż tylko angielski ([pełna lista języków](https://dev.languagetool.org/languages)).
 
Strona: https://languagetool.org/
Repozytorium na GitHubie: https://github.com/languagetool-org/languagetool
Polityka prywatności: https://languagetool.org/legal/privacy

Ich model biznesowy opiera się, o subskrybuje premium (za którą nie trzeba płacić, gdy hostuje się LanguageTool na własnym serwerze), oraz subskrybcję ich Proofreading API.

**Comment by Arturro43** [comment]
Akceptowano!

Sugerowane narzędzie pojawi się na liście wraz z wersją b1.4!
